# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razorapp', '0002_auto_20160609_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='payee',
            name='password',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
