# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 13:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='age',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
