# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsearch', '0002_students_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='SR', max_length=2),
        ),
    ]
