# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('razorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='id',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='pay_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='razorapp.Purchase'),
        ),
    ]
